import { useCallback, useEffect, useState } from 'react'
import { ExternalLink, FileText, ThumbsUp, Upload } from 'lucide-react'
import { api, errorMessage } from '../../api/client'
import { uploadFile } from '../../api/files'
import { EmptyState, ErrorState, LoadingState } from '../../components/AsyncState'

const rowsFrom = data => Array.isArray(data) ? data : data?.content || data?.items || []

export default function AttachmentPanel({ paperId, canUpload = false }) {
  const [items, setItems] = useState([]); const [file, setFile] = useState(null); const [order, setOrder] = useState(''); const [progress, setProgress] = useState(0); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(rowsFrom((await api.get(`/attachments/paper/${paperId}`)).data)) } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) } }, [paperId])
  useEffect(() => { load() }, [load])
  const submit = async event => { event.preventDefault(); if (!file) return; setSaving(true); setProgress(0); setError(''); try { const filePath = await uploadFile({ file, paperId, onProgress: value => setProgress(value.total ? Math.round(value.loaded * 100 / value.total) : 0) }); if (!filePath) throw new Error('The upload completed without a file path.'); await api.post('/attachments', { paperId, fileName: file.name, filePath, displayOrder: order === '' ? null : Number(order) }); setFile(null); setOrder(''); setProgress(0); event.currentTarget.reset(); await load() } catch (err) { setError(errorMessage(err)) } finally { setSaving(false) } }
  const react = async id => { try { await api.post(`/attachments/${id}/reaction`, { reactionType: 'LIKE' }); await load() } catch (err) { setError(errorMessage(err)) } }
  return <div className="page"><section className="panel"><div className="section-title"><div><h3>Attachments</h3><p>PDFs and images attached to this board paper.</p></div></div>{canUpload && <form className="attachment-upload" onSubmit={submit}><label className="secondary file-button"><Upload /> Choose PDF or image<input type="file" required accept="application/pdf,image/png,image/jpeg,image/gif,image/webp" onChange={event => setFile(event.target.files?.[0] || null)} /></label><span>{file?.name || 'No file selected'}</span><label>Display order<input type="number" min="0" value={order} onChange={event => setOrder(event.target.value)} /></label><button className="primary" disabled={!file || saving}>{saving ? `Uploading${progress ? ` ${progress}%` : '…'}` : 'Upload attachment'}</button></form>}{error && <ErrorState error={error} retry={load} />}{loading ? <LoadingState label="Loading attachments…" /> : !items.length ? <EmptyState title="No attachments" detail="Documents added to this paper will appear here." /> : <div className="attachment-grid">{items.map(item => <article key={item.id}><FileText /><div><h4>{item.fileName}</h4><small>Order {item.displayOrder ?? '—'}</small></div><a className="secondary" href={item.filePath} target="_blank" rel="noreferrer"><ExternalLink /> Open</a><button className={`icon-button bordered ${item.currentReaction === 'LIKE' ? 'selected' : ''}`} aria-label="Like attachment" onClick={() => react(item.id)}><ThumbsUp /><span>{item.reactionCounts?.LIKE || 0}</span></button></article>)}</div>}</section></div>
}
