import { useEffect, useMemo, useState } from 'react'
import { BellRing, ChevronLeft, ChevronRight, Save } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api, errorMessage } from '../../api/client'
import { collectionFrom } from '../../api/response'
import { meetingListEndpoint } from '../../auth/permissions'
import { useAuth } from '../../state/AuthContext'
import { getReminderOffsets, reminderOptions, scheduleMeetingReminders, setReminderOffsets } from './reminders'

const sameDay=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()
export default function CalendarPage(){const{user}=useAuth();const now=new Date();const[month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1));const[selected,setSelected]=useState(now);const[meetings,setMeetings]=useState([]);const[offsets,setOffsets]=useState(getReminderOffsets);const[showSettings,setShowSettings]=useState(false);const[notice,setNotice]=useState('');const[error,setError]=useState('')
  useEffect(()=>{api.get(meetingListEndpoint(user)).then(({data})=>setMeetings(collectionFrom(data))).catch(err=>setError(errorMessage(err)))},[user])
  const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(), offset=(new Date(month.getFullYear(),month.getMonth(),1).getDay()+6)%7
  const selectedMeetings=useMemo(()=>meetings.filter(item=>sameDay(new Date(item.meetingDateTime),selected)).sort((a,b)=>new Date(a.meetingDateTime)-new Date(b.meetingDateTime)),[meetings,selected])
  const save=async()=>{if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();setReminderOffsets(offsets);const count=scheduleMeetingReminders(meetings);setNotice(`Reminder preferences saved. ${count} reminder${count===1?'':'s'} scheduled while this browser is running.`)}
  return <div className="page"><div className="page-heading"><div><span className="breadcrumb">Home / Meeting calendar</span><h2>Meeting Calendar</h2><p>Browse your schedule and manage browser reminder preferences.</p></div><button className="secondary" onClick={()=>setShowSettings(v=>!v)}><BellRing/> Reminders</button></div>{notice&&<div className="alert success">{notice}</div>}{error&&<div className="alert error">{error}</div>}{showSettings&&<section className="panel reminder-panel"><h3>Meeting reminders</h3><p>Choose when this browser should notify you before upcoming meetings.</p><div>{Object.entries(reminderOptions).map(([value,label])=><label key={value}><input type="checkbox" checked={offsets.includes(Number(value))} onChange={event=>setOffsets(current=>event.target.checked?[...current,Number(value)]:current.filter(item=>item!==Number(value)))} />{label}</label>)}</div><button className="primary" onClick={save}><Save/> Save and reschedule</button></section>}<div className="calendar-layout"><section className="panel calendar-card"><header><button className="icon-button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><h3>{month.toLocaleString(undefined,{month:'long',year:'numeric'})}</h3><button className="icon-button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></header><div className="calendar-grid weekdays">{['M','T','W','T','F','S','S'].map((day,index)=><b key={`${day}-${index}`}>{day}</b>)}</div><div className="calendar-grid">{Array.from({length:offset},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=new Date(month.getFullYear(),month.getMonth(),i+1),marked=meetings.some(item=>sameDay(new Date(item.meetingDateTime),date));return <button key={i} className={`${sameDay(date,selected)?'selected ':''}${marked?'marked':''}`} onClick={()=>setSelected(date)}>{i+1}</button>})}</div></section><section className="panel calendar-schedule"><h3>{sameDay(selected,now)?"Today's schedule":selected.toLocaleDateString(undefined,{month:'long',day:'numeric'})}</h3>{selectedMeetings.length?selectedMeetings.map(item=><Link key={item.id} to={`/meetings/${item.id}`}><b>{item.title}</b><span>{new Date(item.meetingDateTime).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})} · {item.location||item.type}</span></Link>):<p>No meetings on this date.</p>}</section></div></div>}
