import { useCallback, useEffect, useState } from 'react'
import { MessageCircle, Pencil, Send, Share2, ThumbsUp, Trash2 } from 'lucide-react'
import { api, errorMessage } from '../../api/client'
import { EmptyState, ErrorState, LoadingState } from '../../components/AsyncState'

const rowsFrom = data => Array.isArray(data) ? data : data?.content || data?.items || []

export default function CommentsPanel({ kind, targetId, user, canComment = true }) {
  const endpoint = `/comments/${kind}/${targetId}`
  const [items, setItems] = useState([]); const [text, setText] = useState(''); const [visibility, setVisibility] = useState('ALL_PARTICIPANTS'); const [editing, setEditing] = useState(null); const [replying, setReplying] = useState(null); const [reply, setReply] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(rowsFrom((await api.get(endpoint)).data)) } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) } }, [endpoint])
  useEffect(() => { load() }, [load])
  const payload = value => ({ [`${kind}Id`]: targetId, commentText: value, annotated: false, visibility, pageNumber: null, selectedUserIds: [] })
  const submit = async event => { event.preventDefault(); if (!text.trim()) return; setSaving(true); try { if (editing) await api.put(`/comments/${editing.id}`, payload(text.trim())); else await api.post('/comments', payload(text.trim())); setText(''); setEditing(null); await load() } catch (err) { setError(errorMessage(err)) } finally { setSaving(false) } }
  const remove = async item => { if (!window.confirm('Delete this comment?')) return; try { await api.delete(`/comments/${item.id}`); await load() } catch (err) { setError(errorMessage(err)) } }
  const react = async (item, reactionType) => { try { await api.post(`/comments/${item.id}/reaction`, { reactionType }); await load() } catch (err) { setError(errorMessage(err)) } }
  const sendReply = async item => { if (!reply.trim()) return; try { await api.post(`/comments/${item.id}/replies`, { message: reply.trim() }); setReply(''); setReplying(null); await load() } catch (err) { setError(errorMessage(err)) } }
  const share = async item => { const value = window.prompt('User ID to share this comment with'); if (!value) return; try { await api.post('/comments/share', { commentId: item.id, sharedByUserId: user.id, sharedToUserId: Number(value) }) } catch (err) { setError(errorMessage(err)) } }
  return <div className="page"><section className="panel comments-panel"><div className="section-title"><div><h3>Comments</h3><p>Discuss this {kind} with authorized participants.</p></div></div>{canComment && <form className="comment-compose" onSubmit={submit}><textarea required value={text} onChange={event => setText(event.target.value)} placeholder="Write a comment…" /><div><select value={visibility} onChange={event => setVisibility(event.target.value)}><option value="ALL_PARTICIPANTS">All participants</option><option value="PRIVATE">Private</option><option value="SELECTED_USERS">Selected users</option></select><button className="primary" disabled={saving}><Send />{editing ? 'Update' : 'Post comment'}</button>{editing && <button type="button" className="secondary" onClick={() => { setEditing(null); setText('') }}>Cancel</button>}</div></form>}{error && <ErrorState error={error} retry={load} />}{loading ? <LoadingState label="Loading comments…" /> : !items.length ? <EmptyState title="No comments yet" /> : <div className="comment-thread">{items.map(item => <article key={item.id}><header><b>{item.createdByUsername || 'User'}</b><small>{item.createdAt ? new Date(item.createdAt).toLocaleString() : ''}</small><span className="badge muted">{item.visibility || 'ALL_PARTICIPANTS'}</span></header><p>{item.commentText}</p><div className="comment-actions"><button onClick={() => react(item, 'LIKE')} className={item.currentReaction === 'LIKE' ? 'selected' : ''}><ThumbsUp />{item.reactionCounts?.LIKE || item.reactionCount || 0}</button><button onClick={() => setReplying(replying === item.id ? null : item.id)}><MessageCircle />Reply</button><button onClick={() => share(item)}><Share2 />Share</button>{item.ownedByCurrentUser && <><button onClick={() => { setEditing(item); setText(item.commentText); setVisibility(item.visibility || 'ALL_PARTICIPANTS') }}><Pencil />Edit</button><button onClick={() => remove(item)}><Trash2 />Delete</button></>}</div>{(item.replies || []).map(value => <div className="comment-reply" key={value.id}><b>{value.createdByUsername || 'User'}</b><p>{value.message}</p></div>)}{replying === item.id && <div className="reply-compose"><input autoFocus value={reply} onChange={event => setReply(event.target.value)} placeholder="Write a reply…" /><button className="primary" onClick={() => sendReply(item)}>Reply</button></div>}</article>)}</div>}</section></div>
}
