import { useEffect, useState } from 'react'
import { CheckCircle2, ShieldAlert } from 'lucide-react'
import { api, errorMessage } from '../../api/client'
import { collectionFrom } from '../../api/response'

export default function AccessValidationPage(){const[users,setUsers]=useState([]);const[userId,setUserId]=useState('');const[channel,setChannel]=useState('WEB');const[result,setResult]=useState(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('')
 useEffect(()=>{api.get('/users').then(({data})=>setUsers(collectionFrom(data))).catch(err=>setError(errorMessage(err)))},[])
 const submit=async event=>{event.preventDefault();setBusy(true);setError('');setResult(null);try{setResult((await api.get(`/access-control/validate/${userId}`,{params:{channel}})).data)}catch(err){setError(errorMessage(err))}finally{setBusy(false)}}
 return <div className="page"><div className="page-heading"><div><span className="breadcrumb">Home / Access control</span><h2>Access Control</h2><p>Validate whether a user may connect through a selected channel.</p></div></div><section className="panel access-validation"><form onSubmit={submit}><label>User<select required value={userId} onChange={event=>setUserId(event.target.value)}><option value="">Select user...</option>{users.map(user=><option value={user.id} key={user.id}>{user.displayName||user.username} ({user.username})</option>)}</select></label><label>Channel<select value={channel} onChange={event=>setChannel(event.target.value)}><option value="WEB">Web</option><option value="DEVICE">Device</option></select></label><button className="primary" disabled={busy}>{busy?'Checking...':'Validate access'}</button></form>{error&&<div className="alert error">{error}</div>}{result&&<article className={`access-result ${result.allowed?'allowed':'denied'}`}>{result.allowed?<CheckCircle2/>:<ShieldAlert/>}<div><h3>{result.allowed?'Access allowed':'Access denied'}</h3><p><b>{result.username}</b> · {result.requestedChannel}</p><span>{result.reason||'No additional reason supplied.'}</span></div></article>}</section></div>}
