const d=(key,control='toggle',extra={})=>({key,label:key.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase()),control,defaultValue:control==='toggle'?'false':'',...extra})
const n=(key,value='0',extra={})=>d(key,'number',{defaultValue:value,...extra})
const s=(key,options,value=options[0])=>d(key,'select',{options,defaultValue:value})
const m=(key,options,value=options.join(','),extra={})=>d(key,'multi',{options,defaultValue:value,...extra})

export const settingDefinitions={
 MEETING_CIRCULAR:[
  d('display_circular_date','toggle',{defaultValue:'true'}),n('participant_status_block_minutes','10'),d('meeting_pending_approval_indicator'),d('circular_pending_approval_indicator'),n('past_meeting_search_count','100'),d('view_action_items','toggle',{defaultValue:'true'}),d('add_action_items','toggle',{defaultValue:'true',enabledBy:'view_action_items'}),d('select_all_sharing'),
  m('meeting_approval_options',['Approve','Reject','Abstain','Interest','RPT'],'Approve,Reject,Abstain'),m('circular_approval_options',['Approve','Reject','Abstain','Interest','RPT'],'Approve,Reject,Abstain'),d('meeting_notes','toggle',{defaultValue:'true'}),d('meeting_request_reason'),d('meeting_unapproved_alert_enabled'),n('meeting_unapproved_alert_days','1',{enabledBy:'meeting_unapproved_alert_enabled'}),d('circular_unapproved_alert_enabled'),n('circular_unapproved_alert_days','1',{enabledBy:'circular_unapproved_alert_enabled'}),d('email_shared_comment','toggle',{defaultValue:'true'}),d('email_shared_annotation','toggle',{defaultValue:'true'}),d('agenda_item_subcategory_sharing'),d('allow_past_meetings','toggle',{defaultValue:'true'}),d('allow_change_passed_meeting_dates','toggle',{defaultValue:'true'}),n('action_item_expiry_alert_days','2')],
 AGENDA:[d('share_templates_across_categories','toggle',{defaultValue:'true'}),d('custom_agenda_headings','toggle',{defaultValue:'true'}),d('agenda_auto_numbering'),d('expand_agenda_papers','toggle',{defaultValue:'true'})],
 PAPER:[
  d('approval_confirmation','toggle',{defaultValue:'true'}),d('meeting_papers_only_approval'),d('member_email_annotated_paper','toggle',{defaultValue:'true'}),d('secretary_email_annotated_paper','toggle',{defaultValue:'true'}),d('secretary_email_annotated_comments','toggle',{defaultValue:'true'}),d('member_email_annotated_comments','toggle',{defaultValue:'true'}),d('pending_approval_alert'),n('pending_approval_alert_days','7',{enabledBy:'pending_approval_alert'}),d('paper_clipboard_copy'),d('clear_closed_meeting_papers','toggle',{defaultValue:'true'}),s('paper_scroll_direction',['Right-Left','Up-Down']),d('secretary_printing','toggle',{defaultValue:'true'}),d('member_printing'),d('approval_comments','toggle',{defaultValue:'true'}),d('view_others_approval_comments','toggle',{defaultValue:'true'}),d('email_on_paper_approval'),s('watermark_type',['First name and Last name','Username','Email address','None']),d('printing_disclaimer','text',{defaultValue:'This document is confidential and intended solely for the use of authorized recipients.'}),m('annotation_tools',['Text Highlighter','Pen','Annotated Comments','Audio annotation','Bookmark','Annotation list','Annotated document version','Image Highlighter','Share Annotated documents','Search','Signature']),d('pack_delivery_report','toggle',{defaultValue:'true'}),d('mandatory_paper_reference'),d('unique_paper_reference'),d('esignature_meeting_date'),d('esignature_approval_date'),n('past_paper_search_count','50')],
 USER_MANAGEMENT:[
  n('display_name_length','20',{max:20}),d('display_deactivated_users_device'),d('logout_confirmation','toggle',{defaultValue:'true'}),d('display_deleted_users_device'),d('annotation_backup'),n('annotation_backup_frequency','7',{enabledBy:'annotation_backup'}),n('annotation_backup_threshold','0',{enabledBy:'annotation_backup'}),d('remember_username','toggle',{defaultValue:'true'}),d('remember_username_all','toggle',{defaultValue:'true',enabledBy:'remember_username'}),d('secretary_email_copy','toggle',{defaultValue:'true'}),d('display_deleted_users_web'),d('two_step_authentication'),n('verification_code_expiry','5',{enabledBy:'two_step_authentication'}),n('verification_code_remember_days','30',{enabledBy:'two_step_authentication'}),d('privilege_change_email'),s('disclaimer_mode',['No Disclaimer Note','Show on Login','Require Acceptance']),d('salutations','text',{defaultValue:'Mr.,Mrs.,Ms.,Dr.'})],
 COMMENT:[
  d('comment_select_all','toggle',{defaultValue:'true'}),d('member_email_comments'),d('restrict_meeting_comments'),m('meeting_comment_roles',['Secretary - Paper Comments','Member - Paper Comments','Secretary - Meeting Comments','Member - Meeting Comments'],'',{enabledBy:'restrict_meeting_comments'}),d('restrict_circular_comments'),m('circular_comment_roles',['Secretary - Paper Comments','Member - Paper Comments','Secretary - Meeting Comments','Member - Meeting Comments'],'',{enabledBy:'restrict_circular_comments'}),d('side_by_side_comments'),d('agenda_comment_clipboard'),d('meeting_comment_clipboard')],
 GENERAL:[m('whats_new',['New Meetings/Circulars','New Agenda Items','Amended Agenda Items','Pending Approvals','Paper Comments','Meeting/Circular Comments','Shared Annotated Papers','Shared Documents','News'])],
}
