import { useEffect, useState } from 'react'
import { Save } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { api, errorMessage } from '../../api/client'
import { useAuth } from '../../state/AuthContext'
import { settingDefinitions } from './settingDefinitions'

const names = { MEETING_CIRCULAR: 'Meeting & Circular', AGENDA: 'Agenda', PAPER: 'Paper', USER_MANAGEMENT: 'User Management', COMMENT: 'Comment', GENERAL: 'General' }

export function SettingGroupPage() {
  const { group } = useParams(); const definitions=settingDefinitions[group]||[]; const [drafts, setDrafts] = useState({})
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false)
  const load = async () => { setError(''); try { const { data } = await api.get(`/settings/group/${group}`); const stored=Object.fromEntries(data.map(item=>[item.settingKey,item.settingValue])); setDrafts(Object.fromEntries(definitions.map(item=>[item.key,stored[item.key]??item.defaultValue]))) } catch (err) { setError(errorMessage(err)) } }
  useEffect(() => { load() }, [group])
  const save = async () => { setSaving(true); setError(''); try { for(const item of definitions) await api.post('/settings',{settingGroup:group,settingKey:item.key,settingValue:String(drafts[item.key]??item.defaultValue),description:item.label});setNotice('Settings saved successfully.');await load() }catch(err){setError(errorMessage(err))}finally{setSaving(false)} }
  const change=(key,value)=>setDrafts(current=>({...current,[key]:value})); const toggleOption=(item,option)=>{const selected=new Set(String(drafts[item.key]||'').split(',').filter(Boolean));selected.has(option)?selected.delete(option):selected.add(option);change(item.key,[...selected].join(','))}
  return <div className="page"><div className="page-heading"><div><span className="breadcrumb">Home / Settings / {names[group] || group}</span><h2>{names[group] || 'Settings'}</h2><p>Configure the same web and device behavior available in the mobile application.</p></div><button className="primary" disabled={saving} onClick={save}><Save/>{saving?'Saving...':'Save all'}</button></div>{notice&&<div className="alert success">{notice}</div>}{error&&<div className="alert error">{error}</div>}<div className="settings-list">{definitions.map(item=>{const value=drafts[item.key]??item.defaultValue,disabled=item.enabledBy&&String(drafts[item.enabledBy]).toLowerCase()!=='true';return <section className={`panel setting-row ${disabled?'setting-disabled':''}`} key={item.key}><div><h3>{item.label}</h3>{item.enabledBy&&<p>Depends on {item.enabledBy.replaceAll('_',' ')}</p>}</div><div className="setting-control">{item.control==='toggle'?<label className="toggle"><input type="checkbox" disabled={disabled} checked={String(value).toLowerCase()==='true'} onChange={event=>change(item.key,String(event.target.checked))}/><span>{String(value).toLowerCase()==='true'?'Enabled':'Disabled'}</span></label>:item.control==='select'?<select disabled={disabled} value={value} onChange={event=>change(item.key,event.target.value)}>{item.options.map(option=><option key={option}>{option}</option>)}</select>:item.control==='multi'?<div className="setting-chips">{item.options.map(option=><button type="button" disabled={disabled} className={String(value).split(',').includes(option)?'selected':''} onClick={()=>toggleOption(item,option)} key={option}>{option}</button>)}</div>:<input disabled={disabled} type={item.control==='number'?'number':'text'} min="0" max={item.max} value={value} onChange={event=>change(item.key,event.target.value)}/>}</div></section>})}</div></div>
}

export function IssueReportPage() {
  const { user } = useAuth(); const [form, setForm] = useState({ issueOccurredDate: new Date().toISOString().slice(0,10), issueDescription: '', username: user?.username || '', screenshotPath: '', attachLogFiles: true, attachProductSettings: true, attachErrorData: true, otherResources: '' })
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [done, setDone] = useState('')
  const submit = async event => { event.preventDefault(); setBusy(true); setError(''); try { const { data } = await api.post('/issues', form); setDone(typeof data === 'string' ? data : 'Issue report submitted.'); setForm({ ...form, issueDescription: '', screenshotPath: '', otherResources: '' }) } catch (err) { setError(errorMessage(err)) } finally { setBusy(false) } }
  const update = event => setForm({ ...form, [event.target.name]: event.target.type === 'checkbox' ? event.target.checked : event.target.value })
  return <div className="page"><div className="page-heading"><div><span className="breadcrumb">Home / Report an issue</span><h2>Report an issue</h2><p>Send diagnostics and context to the support workflow.</p></div></div><section className="panel issue-panel"><form className="form-grid" onSubmit={submit}><label>Date occurred<input type="date" name="issueOccurredDate" required value={form.issueOccurredDate} onChange={update} /></label><label>Username<input name="username" required value={form.username} onChange={update} /></label><label className="full">Description<textarea name="issueDescription" required value={form.issueDescription} onChange={update} /></label><label className="full">Screenshot path<input name="screenshotPath" value={form.screenshotPath} onChange={update} placeholder="Optional server-accessible path" /></label><label><input type="checkbox" name="attachLogFiles" checked={form.attachLogFiles} onChange={update} /> Attach log files</label><label><input type="checkbox" name="attachProductSettings" checked={form.attachProductSettings} onChange={update} /> Attach product settings</label><label><input type="checkbox" name="attachErrorData" checked={form.attachErrorData} onChange={update} /> Attach error data</label><label className="full">Other resources<textarea name="otherResources" value={form.otherResources} onChange={update} /></label>{done && <div className="alert success full">{done}</div>}{error && <div className="alert error full">{error}</div>}<div className="form-actions full"><button className="primary" disabled={busy}>{busy ? 'Submitting...' : 'Submit issue report'}</button></div></form></section></div>
}
