enum SettingControl { toggle, number, text, select, multiSelect }

class SettingDefinition {
  final String key;
  final String label;
  final String section;
  final SettingControl control;
  final String defaultValue;
  final String? suffix;
  final String? helper;
  final List<String> options;
  final String? enabledBy;
  final bool indented;
  final int? max;

  const SettingDefinition(
    this.key,
    this.label,
    this.section,
    this.control, {
    this.defaultValue = 'false',
    this.suffix,
    this.helper,
    this.options = const [],
    this.enabledBy,
    this.indented = false,
    this.max,
  });
}

const _d = 'Device';
const _w = 'Web';
const _b = 'Web and Device';

const Map<String, List<SettingDefinition>> settingDefinitions = {
  'MEETING_CIRCULAR': [
    SettingDefinition(
      'display_circular_date',
      'Display the Circular date on Device',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'participant_status_block_minutes',
      'Duration to block selecting of meeting participant status by Board Member',
      _d,
      SettingControl.number,
      defaultValue: '10',
      suffix: 'minutes before starting of meeting',
    ),
    SettingDefinition(
      'meeting_pending_approval_indicator',
      'Dashboard indicator for Meetings with pending paper approvals',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'circular_pending_approval_indicator',
      'Dashboard indicator for Circulars with pending paper approvals',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'past_meeting_search_count',
      'Past Meetings or Circulars search result count',
      _d,
      SettingControl.number,
      defaultValue: '100',
    ),
    SettingDefinition(
      'view_action_items',
      'Enable members to view action items from the device',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'add_action_items',
      'Enable members to add action items from the device',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
      enabledBy: 'view_action_items',
      indented: true,
    ),
    SettingDefinition(
      'select_all_sharing',
      'Set “Select All” as ticked for all sharing options',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'meeting_approval_options',
      'Approval options for Meeting Papers',
      _b,
      SettingControl.multiSelect,
      defaultValue: 'Approve,Reject,Abstain',
      options: ['Approve', 'Reject', 'Abstain', 'Interest', 'RPT'],
    ),
    SettingDefinition(
      'circular_approval_options',
      'Approval options for Circular Papers',
      _b,
      SettingControl.multiSelect,
      defaultValue: 'Approve,Reject,Abstain',
      options: ['Approve', 'Reject', 'Abstain', 'Interest', 'RPT'],
    ),
    SettingDefinition(
      'meeting_notes',
      'Enable Meeting notes for Board Members',
      _b,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'meeting_request_reason',
      'Display a reason field for Decline/Tentative/Cancel meeting requests',
      _b,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'meeting_unapproved_alert_enabled',
      'Email alert for un-approved Meeting papers',
      _b,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'meeting_unapproved_alert_days',
      'Lead time prior to Meeting date',
      _b,
      SettingControl.number,
      defaultValue: '1',
      suffix: 'days',
      enabledBy: 'meeting_unapproved_alert_enabled',
      indented: true,
    ),
    SettingDefinition(
      'circular_unapproved_alert_enabled',
      'Email alert for un-approved Circular papers',
      _b,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'circular_unapproved_alert_days',
      'Lead time prior to Circular target date',
      _b,
      SettingControl.number,
      defaultValue: '1',
      suffix: 'days',
      enabledBy: 'circular_unapproved_alert_enabled',
      indented: true,
    ),
    SettingDefinition(
      'email_shared_comment',
      'Email notification when a member shares a comment',
      _b,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'email_shared_annotation',
      'Email notification when a member shares an annotated paper',
      _b,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'agenda_item_subcategory_sharing',
      'Enable Agenda item sharing within Subcategories',
      _b,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'allow_past_meetings',
      'Enable creation of meetings with past dates',
      _b,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'allow_change_passed_meeting_dates',
      'Enable changes to open meeting dates that have passed',
      _b,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'action_item_expiry_alert_days',
      'Days before Action item expiry to send an alert',
      _b,
      SettingControl.number,
      defaultValue: '2',
      suffix: 'days',
    ),
  ],
  'AGENDA': [
    SettingDefinition(
      'share_templates_across_categories',
      'Allow sharing Agenda templates across Category and/or Subcategory',
      _w,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'custom_agenda_headings',
      'Allow customized headings/sub-headings in Agenda',
      _w,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'agenda_auto_numbering',
      'Generate auto numbering for Agenda Items',
      _b,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'expand_agenda_papers',
      'Expand and display main paper and attachments in the Agenda',
      _b,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
  ],
  'PAPER': [
    SettingDefinition(
      'approval_confirmation',
      'Confirmation message prior to approval',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'meeting_papers_only_approval',
      'Block approvals for Meeting Papers only',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'member_email_annotated_paper',
      'Board Member can email annotated paper with comments',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'secretary_email_annotated_paper',
      'Board Secretary can email annotated paper with comments',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'secretary_email_annotated_comments',
      'Board Secretary can email annotated comments',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'member_email_annotated_comments',
      'Board Member can email annotated comments',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'pending_approval_alert',
      'Display Pending Approval Alert',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'pending_approval_alert_days',
      'Display alert for pending approvals',
      _d,
      SettingControl.number,
      defaultValue: '7',
      suffix: 'days',
      enabledBy: 'pending_approval_alert',
      indented: true,
    ),
    SettingDefinition(
      'paper_clipboard_copy',
      'Allow clipboard text copy for papers',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'clear_closed_meeting_papers',
      'Clear closed Meeting Papers on device',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'paper_scroll_direction',
      'Paper scrolling direction',
      _d,
      SettingControl.select,
      defaultValue: 'Right-Left',
      options: ['Right-Left', 'Up-Down'],
    ),
    SettingDefinition(
      'secretary_printing',
      'Enable paper printing for Board Secretary',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'member_printing',
      'Enable paper printing for Board Members',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'approval_comments',
      'Enable approval comments for Board Members',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'view_others_approval_comments',
      'Allow members to view approval comments of other members',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'email_on_paper_approval',
      'Email notification when a member approves a paper',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'watermark_type',
      'Watermark Type',
      _d,
      SettingControl.select,
      defaultValue: 'First name and Last name',
      options: [
        'First name and Last name',
        'Username',
        'Email address',
        'None',
      ],
    ),
    SettingDefinition(
      'printing_disclaimer',
      'Disclaimer shown when emailing or printing an Agenda item',
      _d,
      SettingControl.text,
      defaultValue:
          'This document is confidential and intended solely for the use of authorized recipients.',
    ),
    SettingDefinition(
      'annotation_tools',
      'Enabled annotation tools',
      _d,
      SettingControl.multiSelect,
      defaultValue:
          'Text Highlighter,Pen,Annotated Comments,Audio annotation,Bookmark,Annotation list,Annotated document version,Image Highlighter,Share Annotated documents,Search,Signature',
      options: [
        'Text Highlighter',
        'Pen',
        'Annotated Comments',
        'Audio annotation',
        'Bookmark',
        'Annotation list',
        'Annotated document version',
        'Image Highlighter',
        'Share Annotated documents',
        'Search',
        'Signature',
      ],
    ),
    SettingDefinition(
      'pack_delivery_report',
      'Enable Pack Delivery Report',
      _w,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'mandatory_paper_reference',
      'Mandatory Paper reference number',
      _w,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'unique_paper_reference',
      'Unique Paper reference number',
      _w,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'esignature_meeting_date',
      'Display Meeting/Circular date on E-signature status page',
      _w,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'esignature_approval_date',
      'Display Approval date on E-signature status page',
      _w,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'past_paper_search_count',
      'Past paper search result count',
      _b,
      SettingControl.number,
      defaultValue: '50',
    ),
  ],
  'USER_MANAGEMENT': [
    SettingDefinition(
      'display_name_length',
      'Display Name Length',
      _d,
      SettingControl.number,
      defaultValue: '20',
      helper: 'Maximum allowed length is 20',
      max: 20,
    ),
    SettingDefinition(
      'display_deactivated_users_device',
      'Display deactivated users on Device',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'logout_confirmation',
      'Display confirmation alert at Logout',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'display_deleted_users_device',
      'Display deleted users on Device',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'annotation_backup',
      'Enable Annotation Backup & Restore',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'annotation_backup_frequency',
      'Frequency to Backup Annotations',
      _d,
      SettingControl.number,
      defaultValue: '7',
      suffix: 'days',
      enabledBy: 'annotation_backup',
      indented: true,
    ),
    SettingDefinition(
      'annotation_backup_threshold',
      'Annotations required to begin backup',
      _d,
      SettingControl.number,
      defaultValue: '0',
      enabledBy: 'annotation_backup',
      indented: true,
    ),
    SettingDefinition(
      'remember_username',
      'Remember username on device',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'remember_username_all',
      'Enable “Remember my username” for all users',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
      enabledBy: 'remember_username',
      indented: true,
    ),
    SettingDefinition(
      'secretary_email_copy',
      'Enable Email Copy option for Board Secretary',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'display_deleted_users_web',
      'Display Deleted Users on Web',
      _w,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'two_step_authentication',
      'Enable 2-step authentication',
      _w,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'verification_code_expiry',
      'Duration until verification code expires',
      _w,
      SettingControl.number,
      defaultValue: '5',
      suffix: 'minutes',
      enabledBy: 'two_step_authentication',
      indented: true,
    ),
    SettingDefinition(
      'verification_code_remember_days',
      'Remember verification for login',
      _w,
      SettingControl.number,
      defaultValue: '30',
      suffix: 'days',
      enabledBy: 'two_step_authentication',
      indented: true,
    ),
    SettingDefinition(
      'privilege_change_email',
      'Email notifications for user privilege changes',
      _w,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'disclaimer_mode',
      'Enable disclaimer',
      _b,
      SettingControl.select,
      defaultValue: 'No Disclaimer Note',
      options: ['No Disclaimer Note', 'Show on Login', 'Require Acceptance'],
    ),
    SettingDefinition(
      'salutations',
      'Salutations (comma separated)',
      _b,
      SettingControl.text,
      defaultValue: 'Mr.,Mrs.,Ms.,Dr.',
    ),
  ],
  'COMMENT': [
    SettingDefinition(
      'comment_select_all',
      'Enable “Select all” for sharing comments/annotated papers',
      _d,
      SettingControl.toggle,
      defaultValue: 'true',
    ),
    SettingDefinition(
      'member_email_comments',
      'Enable Board Member to email comments',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'restrict_meeting_comments',
      'Restrict commenting outside Meeting duration',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'meeting_comment_roles',
      'Meeting comment permissions',
      _d,
      SettingControl.multiSelect,
      options: [
        'Secretary - Paper Comments',
        'Member - Paper Comments',
        'Secretary - Meeting Comments',
        'Member - Meeting Comments',
      ],
      enabledBy: 'restrict_meeting_comments',
      indented: true,
    ),
    SettingDefinition(
      'restrict_circular_comments',
      'Restrict commenting outside Circular duration',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'circular_comment_roles',
      'Circular comment permissions',
      _d,
      SettingControl.multiSelect,
      options: [
        'Secretary - Paper Comments',
        'Member - Paper Comments',
        'Secretary - Meeting Comments',
        'Member - Meeting Comments',
      ],
      enabledBy: 'restrict_circular_comments',
      indented: true,
    ),
    SettingDefinition(
      'side_by_side_comments',
      'Side-by-side Agenda item comments view',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'agenda_comment_clipboard',
      'Allow clipboard copy for Agenda item comments',
      _d,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'meeting_comment_clipboard',
      'Allow clipboard copy for Meeting/Circular comments',
      _d,
      SettingControl.toggle,
    ),
  ],
  'GENERAL': [
    SettingDefinition(
      'whats_new',
      'Items shown in What’s New',
      _d,
      SettingControl.multiSelect,
      defaultValue:
          'New Meetings/Circulars,New Agenda Items,Amended Agenda Items,Pending Approvals,Paper Comments,Meeting/Circular Comments,Shared Annotated Papers,Shared Documents,News',
      options: [
        'New Meetings/Circulars',
        'New Agenda Items',
        'Amended Agenda Items',
        'Pending Approvals',
        'Paper Comments',
        'Meeting/Circular Comments',
        'Shared Annotated Papers',
        'Shared Documents',
        'News',
      ],
    ),
  ],
  'SURVEY': [
    SettingDefinition(
      'display_survey_responder',
      'Display Responder Option',
      _w,
      SettingControl.toggle,
    ),
    SettingDefinition(
      'survey_reminder_days',
      'Send Survey reminder alert before',
      _w,
      SettingControl.number,
      defaultValue: '2',
      suffix: 'days',
    ),
  ],
};
