import { useState } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { ArrowRight, Eye, EyeOff, ShieldCheck } from 'lucide-react'
import { errorMessage } from '../api/client'
import { useAuth } from '../state/AuthContext'

function AuthFrame({ children, title, subtitle }) { return <div className="auth-page"><section className="auth-visual"><img src="/assets/slpa_logo.png" alt="SLPA logo"/><div><span className="eyebrow">Secure board governance</span><h1>Decisions made clearer.<br/>Leadership made stronger.</h1><p>A secure digital workspace for meetings, papers, approvals and board collaboration.</p></div><footer>Sri Lanka Ports Authority · Board Management System</footer></section><section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><img src="/assets/slpa_logo.png" alt=""/><b>SLPA Board</b></div><span className="eyebrow">Welcome</span><h2>{title}</h2><p>{subtitle}</p>{children}</div></section></div> }

export function LoginPage() {
  const { user, login } = useAuth(); const navigate = useNavigate(); const [form,setForm] = useState({username:'',password:''}); const [show,setShow]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  if (user) return <Navigate to="/dashboard" replace />
  const submit=async(e)=>{e.preventDefault();setBusy(true);setError('');try{const twoFactor=await login(form);navigate(twoFactor?'/verify-2fa':'/dashboard')}catch(err){setError(errorMessage(err))}finally{setBusy(false)}}
  return <AuthFrame title="Sign in to your workspace" subtitle="Enter your credentials to continue."><form onSubmit={submit}><label>Username<input autoFocus required value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="Enter your username"/></label><label>Password<div className="password"><input required type={show?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Enter your password"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="alert error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Signing in…':<>Sign in <ArrowRight/></>}</button></form><p className="auth-help">Having trouble? Contact your board administrator.</p></AuthFrame>
}
export function VerifyPage(){const {challenge,verify,user}=useAuth();const nav=useNavigate();const [code,setCode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);if(user)return <Navigate to="/dashboard"/>;if(!challenge)return <Navigate to="/login"/>;const submit=async(e)=>{e.preventDefault();setBusy(true);try{await verify(code);nav('/dashboard')}catch(err){setError(errorMessage(err));setBusy(false)}};return <AuthFrame title="Verify your identity" subtitle={`Enter the security code sent for ${challenge.username}.`}><form onSubmit={submit}><div className="verify-icon"><ShieldCheck/></div><label>Six-digit code<input className="otp" inputMode="numeric" pattern="[0-9]{6}" maxLength="6" required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label>{error&&<div className="alert error">{error}</div>}<button className="primary wide" disabled={busy||code.length!==6}>{busy?'Verifying…':'Verify and continue'}</button><button type="button" className="text-button" onClick={()=>nav('/login')}>Back to sign in</button></form></AuthFrame>}
