import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { CalendarDays, ChevronLeft, Clock3, FileText, ListTree, MapPin, MessageSquare, Users } from 'lucide-react'
import ResourcePage from './ResourcePage'
import { useAuth } from '../state/AuthContext'
import { api } from '../api/client'

const TabHeader=({title,description,tabs,tab,setTab})=><div className="page workspace-heading"><h2>{title}</h2><p>{description}</p><div className="tabs">{tabs.map(name=><button type="button" className={tab===name?'active':''} onClick={()=>setTab(name)} key={name}>{name}</button>)}</div></div>

export function MeetingWorkspace(){const {id}=useParams();const meetingId=Number(id);const {user,role}=useAuth();const [tab,setTab]=useState('agenda');const [meeting,setMeeting]=useState(null);const manager=role==='SECRETARY';useEffect(()=>{api.get('/meetings').then(({data})=>setMeeting((Array.isArray(data)?data:data.content||[]).find(item=>Number(item.id)===meetingId)||null))},[meetingId]);return <div><section className="meeting-detail-hero"><Link to="/meetings" className="meeting-back"><ChevronLeft/> Meetings</Link><div className="meeting-detail-main"><div className="meeting-date-icon"><CalendarDays/></div><div><div className="meeting-kicker"><span>{meeting?.type||'MEETING'}</span><span className={`badge ${String(meeting?.status||'').toLowerCase()}`}>{meeting?.status||'Loading'}</span></div><h2>{meeting?.title||`Meeting #${id}`}</h2><p>{meeting?.description||'Open the agenda or meeting papers below.'}</p><div className="meeting-meta">{meeting?.meetingDateTime&&<span><Clock3/>{new Date(meeting.meetingDateTime).toLocaleString()}</span>}{meeting?.location&&<span><MapPin/>{meeting.location}</span>}</div></div></div><div className="meeting-primary-actions"><button className={tab==='agenda'?'active':''} onClick={()=>setTab('agenda')}><ListTree/><span><b>Agenda</b><small>Sections and agenda items</small></span></button><button className={tab==='papers'?'active':''} onClick={()=>setTab('papers')}><FileText/><span><b>Papers</b><small>Documents for this meeting</small></span></button></div><div className="meeting-secondary-actions"><button className={tab==='participants'?'active':''} onClick={()=>setTab('participants')}><Users/> Participants</button><button className={tab==='comments'?'active':''} onClick={()=>setTab('comments')}><MessageSquare/> Comments</button></div></section>
{tab==='agenda'&&<><ResourcePage title="Agenda Sections" description="Organize the meeting agenda." endpoint={`/agendas/sections/${id}`} createEndpoint={manager?'/agendas/sections':undefined} initialValues={{meetingId}} actions={manager?[{label:'Delete',method:'delete',path:r=>`/agendas/sections/${r.id}`,confirm:'Delete this agenda section?'}]:[]} fields={[{name:'meetingId',type:'hidden'},{name:'title',label:'Title',required:true},{name:'numberLabel',label:'Number label'},{name:'displayOrder',label:'Display order',type:'number'}]}/><ResourcePage title="Agenda Items" description="Add text, papers, images, audio, or video." endpoint={`/agendas/items/${id}`} createEndpoint={manager?'/agendas/items':undefined} initialValues={{meetingId}} fields={[{name:'meetingId',type:'hidden'},{name:'sectionId',label:'Section',optionsEndpoint:`/agendas/sections/${id}`,optionLabel:'title'},{name:'itemType',label:'Item type',type:'select',options:['TEXT','PAPER','IMAGE','AUDIO','VIDEO'],required:true},{name:'title',label:'Title',required:true},{name:'numberLabel',label:'Number label'},{name:'displayOrder',label:'Display order',type:'number'},{name:'description',label:'Description',type:'textarea',full:true},{name:'mediaPath',label:'Media path'}]}/></>} 
{tab==='papers'&&<ResourcePage title="Board Papers" description="Papers attached to this meeting." endpoint={`/papers/meeting/${id}`} createEndpoint={manager?'/papers':undefined} initialValues={{meetingId,requiresApproval:false,isMainPaper:false}} actions={[{label:'Open',link:r=>`/papers/${r.id}`}]} fields={[{name:'meetingId',type:'hidden'},{name:'agendaItemId',label:'Agenda item',optionsEndpoint:`/agendas/items/${id}`,optionLabel:'title'},{name:'paperType',label:'Paper type',type:'select',options:['APPROVAL','INFORMATION','DISCUSSION_ITEM','DISCUSSION_PAPER','SUPPORTING_DOCUMENT'],required:true},{name:'title',label:'Title',required:true},{name:'referenceNumber',label:'Reference number'},{name:'versionNumber',label:'Version',type:'number'},{name:'requiresApproval',label:'Requires approval',type:'checkbox'},{name:'isMainPaper',label:'Main paper',type:'checkbox'},{name:'disclaimerMessage',label:'Disclaimer',type:'textarea',full:true}]}/>} 
{tab==='participants'&&<ResourcePage title="Participants" description="Meeting attendance and status." endpoint={`/meetings/${id}/participants`} createEndpoint={manager?'/meetings/participants':undefined} initialValues={{meetingId}} fields={[{name:'meetingId',type:'hidden'},{name:'userId',label:'Participant',optionsEndpoint:`/meetings/${id}/participant-options`,optionLabel:'displayName',required:true},{name:'displaySequence',label:'Display sequence',type:'number'}]}/>} 
{tab==='comments'&&<ResourcePage title="Comments" description="Meeting discussion." endpoint={`/comments/meeting/${id}`} createEndpoint="/comments" initialValues={{meetingId,createdByUserId:user.id,annotated:false}} fields={[{name:'meetingId',type:'hidden'},{name:'createdByUserId',type:'hidden'},{name:'commentText',label:'Comment',type:'textarea',full:true,required:true},{name:'annotated',label:'Annotated',type:'checkbox'}]}/>}</div>}

export function PaperWorkspace(){const {id}=useParams();const paperId=Number(id);const {user}=useAuth();const [tab,setTab]=useState('attachments');return <div><TabHeader title="Paper workspace" description="Review documents, decisions, comments, annotations and delivery." tabs={['attachments','approvals','comments','annotations','delivery']} tab={tab} setTab={setTab}/>
{tab==='attachments'&&<ResourcePage title="Attachments" description="Files attached to this paper." endpoint={`/attachments/paper/${id}`} createEndpoint="/attachments" initialValues={{paperId}} fields={[{name:'paperId',type:'hidden'},{name:'fileName',label:'File name',required:true},{name:'filePath',label:'Uploaded file path',required:true},{name:'displayOrder',label:'Display order',type:'number'}]}/>} 
{tab==='approvals'&&<ResourcePage title="Approvals" description="Submit a decision for this paper." endpoint={`/approvals/paper/${id}`} createEndpoint="/approvals" initialValues={{paperId,userId:user.id}} fields={[{name:'paperId',type:'hidden'},{name:'userId',type:'hidden'},{name:'approvalStatus',label:'Decision',type:'select',options:['APPROVED','REJECTED','ABSTAINED'],required:true},{name:'approvalComment',label:'Comment',type:'textarea',full:true}]}/>} 
{tab==='comments'&&<ResourcePage title="Comments" description="Paper discussion." endpoint={`/comments/paper/${id}`} createEndpoint="/comments" initialValues={{paperId,createdByUserId:user.id,annotated:false}} fields={[{name:'paperId',type:'hidden'},{name:'createdByUserId',type:'hidden'},{name:'commentText',label:'Comment',type:'textarea',full:true,required:true},{name:'annotated',label:'Annotated',type:'checkbox'}]}/>} 
{tab==='annotations'&&<ResourcePage title="Annotations" description="Your private paper annotations." endpoint={`/annotations/paper/${id}/user/${user.id}`} createEndpoint="/annotations" initialValues={{paperId,userId:user.id}} fields={[{name:'paperId',type:'hidden'},{name:'userId',type:'hidden'},{name:'annotationType',label:'Type',type:'select',options:['TEXT','HIGHLIGHT','DRAWING'],required:true},{name:'pageNumber',label:'Page',type:'number'},{name:'annotationDataJson',label:'Annotation JSON',type:'textarea',full:true,required:true}]}/>} 
{tab==='delivery'&&<ResourcePage title="Pack Delivery" description="Delivery status for this paper." endpoint={`/pack-delivery/paper/${id}`}/>}</div>}
