import { useCallback, useEffect, useState } from 'react'
import { Heart, MessageCircle, Plus, Trash2 } from 'lucide-react'
import { api, errorMessage } from '../../api/client'
import { uploadFile } from '../../api/files'
import { EmptyState, ErrorState, LoadingState } from '../../components/AsyncState'

const rowsFrom = data => Array.isArray(data) ? data : data?.content || data?.items || []

export default function NewsFeed({ canManage }) {
  const [items, setItems] = useState([]); const [open, setOpen] = useState(false); const [form, setForm] = useState({ title: '', content: '', badgeLabel: 'BOARD NEWS' }); const [image, setImage] = useState(null); const [comment, setComment] = useState({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setItems(rowsFrom((await api.get('/news', { params: { limit: 15 } })).data)) } catch (err) { setError(errorMessage(err)) } finally { setLoading(false) } }, [])
  useEffect(() => { const timer = window.setTimeout(load, 500); return () => window.clearTimeout(timer) }, [load])
  const create = async event => { event.preventDefault(); setSaving(true); try { const imageUrls = image ? [await uploadFile({ file: image })] : []; await api.post('/news', { ...form, imageUrls }); setForm({ title: '', content: '', badgeLabel: 'BOARD NEWS' }); setImage(null); setOpen(false); await load() } catch (err) { setError(errorMessage(err)) } finally { setSaving(false) } }
  const remove = async id => { if (!window.confirm('Delete this news post?')) return; try { await api.delete(`/news/${id}`); await load() } catch (err) { setError(errorMessage(err)) } }
  const react = async id => { try { const { data } = await api.post(`/news/${id}/reactions`, { reactionType: 'LOVE' }); setItems(current => current.map(item => item.id === id ? data : item)) } catch (err) { setError(errorMessage(err)) } }
  const sendComment = async id => { const message = comment[id]?.trim(); if (!message) return; try { const { data } = await api.post(`/news/${id}/comments`, { message }); setItems(current => current.map(item => item.id === id ? data : item)); setComment(current => ({ ...current, [id]: '' })) } catch (err) { setError(errorMessage(err)) } }
  return <section className="news-section"><div className="section-title"><div><h3>Board news</h3><p>Updates and conversations from your board.</p></div>{canManage && <button className="primary" onClick={() => setOpen(value => !value)}><Plus />Create news</button>}</div>{open && <form className="panel news-form" onSubmit={create}><input required placeholder="Title" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} /><input required placeholder="Badge label" value={form.badgeLabel} onChange={event => setForm({ ...form, badgeLabel: event.target.value })} /><textarea required placeholder="News content" value={form.content} onChange={event => setForm({ ...form, content: event.target.value })} /><input type="file" accept="image/*" onChange={event => setImage(event.target.files?.[0] || null)} /><button className="primary" disabled={saving}>{saving ? 'Publishing…' : 'Publish'}</button></form>}{error && <ErrorState error={error} retry={load} />}{loading ? <LoadingState label="Loading board news…" /> : !items.length ? <EmptyState title="No board news" /> : <div className="news-grid">{items.map(item => { const images = item.imageUrls?.length ? item.imageUrls : item.imageUrl ? [item.imageUrl] : []; return <article className="panel news-card" key={item.id}>{images[0] && <img src={images[0]} alt="" />}<div className="news-card-head"><span>{item.badgeLabel || 'BOARD NEWS'}</span>{canManage && <button className="icon-button" aria-label="Delete post" onClick={() => remove(item.id)}><Trash2 /></button>}</div><h3>{item.title}</h3><p>{item.content}</p><small>{item.createdByName || 'Board Secretary'} · {item.createdAt ? new Date(item.createdAt).toLocaleString() : ''}</small><div className="news-actions"><button onClick={() => react(item.id)} className={item.currentReaction === 'LOVE' ? 'selected' : ''}><Heart />{item.reactionCounts?.LOVE || 0}</button><span><MessageCircle />{item.comments?.length || 0}</span></div>{(item.comments || []).slice(-3).map(value => <p className="news-comment" key={value.id}><b>{value.userName || 'User'}</b> {value.message}</p>)}<div className="reply-compose"><input value={comment[item.id] || ''} onChange={event => setComment(current => ({ ...current, [item.id]: event.target.value }))} placeholder="Add a comment…" /><button className="secondary" onClick={() => sendComment(item.id)}>Post</button></div></article> })}</div>}</section>
}
