import { Navigate, Route, Routes } from 'react-router-dom'
import { api } from './api/client'
import AppShell from './components/AppShell'
import Dashboard from './pages/Dashboard'
import ResourcePage from './pages/ResourcePage'
import { LoginPage, VerifyPage } from './pages/AuthPages'
import { MeetingWorkspace, PaperWorkspace } from './pages/Workspaces'
import { useAuth } from './state/AuthContext'

const configs = {
  meetings:{title:'Meetings',description:'Plan, organize and monitor board meetings and circulars.',endpoint:'/meetings',createEndpoint:'/meetings',managerRole:'SECRETARY',actions:[{label:'Open',method:'put',path:r=>`/meetings/${r.id}/open`},{label:'Close',method:'put',path:r=>`/meetings/${r.id}/close`},{label:'Delete',method:'delete',path:r=>`/meetings/${r.id}`,confirm:'Delete this meeting and its associated schedule?'}],fields:[{name:'title',label:'Meeting title',required:true,full:true},{name:'type',label:'Type',type:'select',options:['MEETING','CIRCULAR'],required:true},{name:'meetingDateTime',label:'Meeting date',type:'datetime-local',required:true},{name:'targetDateTime',label:'Target date',type:'datetime-local'},{name:'categoryId',label:'Category',optionsEndpoint:'/categories',optionLabel:'displayName',clears:['subcategoryId'],required:true},{name:'subcategoryId',label:'Subcategory',optionsEndpoint:'/subcategories',optionLabel:'displayName',dependsOn:'categoryId',filter:(item,form)=>Number(item.categoryId)===Number(form.categoryId),required:true},{name:'location',label:'Location'},{name:'description',label:'Description',type:'textarea',full:true}]},
  papers:{title:'Board Papers',description:'A secure library of papers, attachments and supporting documents.',endpoint:'/papers',createEndpoint:'/papers',managerRole:'SECRETARY',fields:[{name:'meetingId',label:'Meeting',optionsEndpoint:'/meetings',optionLabel:'title',clears:['agendaItemId'],required:true},{name:'agendaItemId',label:'Agenda item',optionsEndpoint:form=>`/agendas/items/${form.meetingId}`,optionLabel:'title',dependsOn:'meetingId'},{name:'title',label:'Paper title',required:true,full:true},{name:'paperType',label:'Paper type',type:'select',options:['APPROVAL','INFORMATION','DISCUSSION_ITEM','DISCUSSION_PAPER','SUPPORTING_DOCUMENT'],required:true},{name:'referenceNumber',label:'Reference number'},{name:'versionNumber',label:'Version',type:'number'},{name:'requiresApproval',label:'Requires approval',type:'checkbox'},{name:'isMainPaper',label:'Main paper',type:'checkbox'},{name:'disclaimerMessage',label:'Disclaimer',type:'textarea',full:true}]},
  approvals:{title:'Approvals',description:'Monitor board paper decisions and approval progress.',endpoint:'/admin-reports/pending-approvals'},
  users:{title:'Users',description:'Manage accounts, roles and access to the board workspace.',endpoint:'/users',createEndpoint:'/users',managerRole:'ADMIN',actions:[{label:'Activate',method:'put',path:r=>`/users/${r.id}/activate`},{label:'Deactivate',method:'put',path:r=>`/users/${r.id}/deactivate`},{label:'Lock',method:'put',path:r=>`/users/${r.id}/lock`},{label:'Unlock',method:'put',path:r=>`/users/${r.id}/unlock`},{label:'Reset password',method:'put',path:r=>`/users/${r.id}/reset-password`,confirm:'Reset this user’s password?'}],fields:[{name:'username',label:'Username',required:true},{name:'firstName',label:'First name',required:true},{name:'lastName',label:'Last name',required:true},{name:'boardEmail',label:'Board email',type:'email',required:true},{name:'role',label:'Role',type:'select',options:['ADMIN','SECRETARY','MEMBER'],required:true},{name:'password',label:'Temporary password',type:'password',required:true}]},
  categories:{title:'Categories',description:'Organize board content into clear business categories.',endpoint:'/categories',createEndpoint:'/categories',managerRole:'SECRETARY',editable:true,deletable:true,fields:[{name:'name',label:'Name',required:true},{name:'displayName',label:'Display name',required:true},{name:'displayOrder',label:'Display order',type:'number'}]},
  subcategories:{title:'Subcategories',description:'Manage detailed content classifications within categories.',endpoint:'/subcategories',createEndpoint:'/subcategories',managerRole:'SECRETARY',editable:true,deletable:true,fields:[{name:'categoryId',label:'Category',optionsEndpoint:'/categories',optionLabel:'displayName',required:true},{name:'name',label:'Name',required:true},{name:'displayName',label:'Display name',required:true},{name:'displayOrder',label:'Display order',type:'number'}]},
  privileges:{title:'Privileges',description:'Assign category and subcategory responsibilities to members.',endpoint:'/privileges',createEndpoint:'/privileges',managerRole:'SECRETARY',fields:[{name:'userId',label:'User',optionsEndpoint:'/users',optionLabel:'username',required:true},{name:'subcategoryId',label:'Subcategory',optionsEndpoint:'/subcategories',optionLabel:'displayName',required:true},{name:'assignedRole',label:'Assigned role',type:'select',options:['MEMBER','SECRETARY','VIEW_ONLY','COMMENT_ONLY'],required:true},{name:'displaySequence',label:'Display sequence',type:'number'}]},
  devices:{title:'Devices',description:'Review, approve and secure registered board devices.',endpoint:'/devices',actions:[{label:'Approve',method:'put',path:r=>`/devices/${r.id}/approve`},{label:'Deactivate',method:'put',path:r=>`/devices/${r.id}/deactivate`},{label:'Wipe',method:'put',path:r=>`/devices/${r.id}/wipe`,confirm:'Request a remote wipe for this device?'}]},
  'pack-delivery':{title:'Pack Delivery',description:'Track delivery of board packs to participants.',endpoint:user=>`/pack-delivery/user/${user.id}`},
  settings:{title:'Settings',description:'Configure board, meeting, agenda and security preferences.',endpoint:'/settings',createEndpoint:'/settings',fields:[{name:'settingKey',label:'Setting key',required:true},{name:'settingValue',label:'Value',required:true},{name:'settingGroup',label:'Group',required:true}]},
}
function Protected(){return useAuth().user?<AppShell/>:<Navigate to="/login" replace/>}
function Module({name}){const {user,role}=useAuth();const config=configs[name];const canManage=!config.managerRole||role===config.managerRole;const viewAction=name==='meetings'?{label:'View',link:r=>`/meetings/${r.id}`}:name==='papers'?{label:'View',link:r=>`/papers/${r.id}`}:null;return <ResourcePage {...config} rowLink={name==='meetings'?(row=>`/meetings/${row.id}`):undefined} createEndpoint={canManage?config.createEndpoint:undefined} editable={canManage&&config.editable} deletable={canManage&&config.deletable} actions={[...(viewAction?[viewAction]:[]),...(canManage?(config.actions||[]):[])]} endpoint={typeof config.endpoint==='function'?config.endpoint(user):config.endpoint}/>}
function Reports(){return <ResourcePage title="Audit & Reports" description="Review security, usage and governance activity." endpoint="/reports/audit-logs"/>}
function Access(){return <ResourcePage title="Access Validation" description="Validate whether a user can connect through web or a registered device." endpoint="/users" actions={[{label:'Validate',run:async row=>api.get(`/access-control/validate/${row.id}?channel=WEB`)}]}/>}
function NotFound(){return <div className="center-page"><b>404</b><h2>Page not found</h2><p>The page you requested does not exist.</p><a href="/dashboard" className="primary">Return to dashboard</a></div>}
export default function App(){return <Routes><Route path="/login" element={<LoginPage/>}/><Route path="/verify-2fa" element={<VerifyPage/>}/><Route element={<Protected/>}><Route path="/dashboard" element={<Dashboard/>}/>{Object.keys(configs).map(name=><Route key={name} path={`/${name}`} element={<Module name={name}/>}/>)}<Route path="/meetings/:id" element={<MeetingWorkspace/>}/><Route path="/papers/:id" element={<PaperWorkspace/>}/><Route path="/reports" element={<Reports/>}/><Route path="/access-validation" element={<Access/>}/><Route path="/" element={<Navigate to="/dashboard"/>}/></Route><Route path="*" element={<NotFound/>}/></Routes>}
